### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by mdibaiee** [comment]
@ocramz Thank you!

**Comment by mdibaiee** [comment]
@ocramz This part looks weird to me, it makes me think sibe has all those different methods implemented, I think they should be at the same level.

pca

**Comment by ocramz** [comment]
@mdibaiee yeah I was unsure as well. What methods does `sibe` implement?

**Comment by mdibaiee** [comment]
It's the simple, unmodified method and doesn't belong to any one of those methods listed. [PCA](https://en.wikipedia.org/wiki/Principal_component_analysis#Singular_value_decomposition). So that's why I think it should be just under PCA.

**Comment by ocramz** [comment]
@mdibaiee perhaps we can have a "General" subheader in every section and then all the specialized methods as separate subheaders:

* Method
  * General
    * `implementation1`
    * `implementation 2`
  * Specialized 1
  * Specialized 2

**Comment by mdibaiee** [comment]
@ocramz I think that would work well! Thank you

**Pull request merged**
